#!/usr/bin/env python
import sys
import urllib.request
from pathlib import Path

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: ./get-input {year} {day}")
        exit(1)

    session = (Path(__file__).parent / ".session").read_text().strip()
    year, day = sys.argv[1:]

    request = urllib.request.Request(
        f"https://adventofcode.com/{year}/day/{day}/input",
        headers={"Cookie": f"session={session}"},
    )
    response = urllib.request.urlopen(request)

    if response.status == 200:
        input_file = Path(__file__).parent / "aoc-inputs" / year / f"{day}.txt"
        input_file.parent.mkdir(exist_ok=True)
        input_file.write_text(response.read().decode())
    else:
        print(response.read())
