#!/usr/bin/env python
import sys
import urllib.request
from pathlib import Path


def success(file):
    print(str(file.absolute()))
    exit(0)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: ./get-input {year} {day}")
        exit(1)

    session = (Path(__file__).parent / ".session").read_text().strip()
    year, day = sys.argv[1:]

    input_file = Path(__file__).parent / "inputs" / year / f"{day}.txt"

    if input_file.exists():
        success(input_file)

    print("Downloading input file...", file=sys.stderr)
    request = urllib.request.Request(
        f"https://adventofcode.com/{year}/day/{day}/input",
        headers={"Cookie": f"session={session}"},
    )
    response = urllib.request.urlopen(request)

    if response.status == 200:
        input_file.parent.mkdir(parents=True, exist_ok=True)
        input_file.write_text(response.read().decode())
        success(input_file)
    else:
        print(response.read())
        exit(1)
