import XCTest

@testable import Day8

class Day8Tests: XCTestCase {
    func testDay8() {
        let output = main(
            """
            ............
            ........0...
            .....0......
            .......0....
            ....0.......
            ......A.....
            ............
            ............
            ........A...
            .........A..
            ............
            ............
            """
        )

        XCTAssertEqual(output.0, 14)
        XCTAssertEqual(output.1, 34)
    }
}
